// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoRmr29Mjo5-HAAEbkHpW7JFC8OaGHzNU',
    appId: '1:137403065554:android:91548bcc2cd4e5219ef90b',
    messagingSenderId: '137403065554',
    projectId: 'mynotes-flutter-first-project',
    storageBucket: 'mynotes-flutter-first-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFgK4GpSSHq6FFGrsBWuvqplEYomma-UY',
    appId: '1:137403065554:ios:9c2ccd2a726d6d869ef90b',
    messagingSenderId: '137403065554',
    projectId: 'mynotes-flutter-first-project',
    storageBucket: 'mynotes-flutter-first-project.appspot.com',
    iosClientId: '137403065554-0am81htllud2p6evupok3ur90afjv9aj.apps.googleusercontent.com',
    iosBundleId: 'com.hello.mynotes',
  );
}
